"""
DemoBot - Repurposes long-form content into multiple formats
Generated by Agent CLI - SDK Version
Uses Anthropic Agent SDK for automatic agentic loop
"""

from flask import Flask, request, jsonify
from anthropic import Anthropic
from anthropic.agents import Agent
import os
import json
import re

app = Flask(__name__)
client = Anthropic(api_key=os.environ.get('ANTHROPIC_API_KEY'))

CONFIG = {
  "agent_name": "DemoBot",
  "agent_type": "content_repurposer",
  "business_name": "Vibe Marketing",
  "target_customer": "small service businesses",
  "trigger_type": "webhook",
  "tools": [
    "web_search"
  ],
  "brand_voice": "creative, engaging",
  "client_name": "Demo Client"
}

# Define tool functions for SDK

def web_search(query: str):
    """
    Search the web for information
    """
    # TODO: Implement actual tool logic
    print(f"Tool called: web_search")
    return {"result": f"Mock result for web_search"}


@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "healthy", "agent": "DemoBot", "sdk_version": True})

@app.route('/run', methods=['POST'])
def run_agent():
    try:
        input_data = request.json
        print(f"Agent triggered with: {json.dumps(input_data, indent=2)}")

        result = execute_agent(input_data)
        return jsonify(result)

    except Exception as e:
        print(f"Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

def execute_agent(input_data):
    """Main agent execution logic using SDK"""

    prompt = """You are a content repurposing agent for Vibe Marketing.

Take input content and create:
- Twitter/X thread
- LinkedIn post
- Instagram caption
- Email newsletter snippet

Style: creative, engaging"""

    # Format prompt with input data
    try:
        formatted_prompt = prompt.format(**input_data)
    except KeyError as e:
        # If formatting fails, just use the raw input
        formatted_prompt = f"{prompt}\n\nInput: {json.dumps(input_data)}"

    # Create agent with SDK
    agent = Agent(
        client=client,
        model="claude-sonnet-4-20250514",
        system_prompt=formatted_prompt,
        tools=[web_search]
    )

    # Run agent - SDK handles the loop automatically
    result = agent.run("Process this request and provide structured output.")

    # Extract response text
    response_text = result.output if hasattr(result, 'output') else str(result)

    # Try to parse JSON response for Gumloop compatibility
    try:
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            parsed_result = json.loads(json_match.group())
        else:
            parsed_result = {"output": response_text}
    except:
        parsed_result = {"output": response_text}

    return parsed_result

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f"Starting SDK agent on port {port}...")
    app.run(host='0.0.0.0', port=port)
